version: '3'

services:
  postgres:
    image: postgres:11.20-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pricing_engine
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

